name: First Deployment
on:
  push:
    branches: [ master ]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing with ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: '34.234.77.64'
        username: 'ec2-user'
        key: ${{ secrets.ACTION_SECRET_KEY }}
        port: 22
        script: |
          whoami
